services:
  pylint-uploader:
    image: njavilas/pylint-uploader:latest
    ports:
      - "9999:9999"
      
    environment:
      MEILI_SEARCH_URL: "http://meilisearch:7700"  # URL del servicio de MeiliSearch
      MEILI_API_KEY: "masterKey"  # Cambia esto si tienes una clave de API
      DROP: "false"  # Cambia a "true" si deseas eliminar el índice al iniciar
      PORT: "9999"
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.11

    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterKey"  # Cambia esto a una clave más segura
    volumes:
      - meili_data:/meili_data  # Persistencia de datos

volumes:
  meili_data: